# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GoSsh < Formula
  desc "Minimalist SSH key management tool with interactive TUI"
  homepage "https://github.com/mr-kaynak/go-ssh"
  version "0.1.3"
  license "MIT"

  on_macos do
    on_intel do
      url "https://github.com/mr-kaynak/go-ssh/releases/download/v0.1.3/go-ssh_0.1.3_darwin_amd64.tar.gz"
      sha256 "dead8641a9fc6e5b4b2a41eb285c83c605f5b72081ff84cb48d75a25dea99bf5"

      def install
        bin.install "go-ssh"
      end
    end
    on_arm do
      url "https://github.com/mr-kaynak/go-ssh/releases/download/v0.1.3/go-ssh_0.1.3_darwin_arm64.tar.gz"
      sha256 "3327555c140b0502224b14125463d6f8530597d3a74b395a15f475045cdacd69"

      def install
        bin.install "go-ssh"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/mr-kaynak/go-ssh/releases/download/v0.1.3/go-ssh_0.1.3_linux_amd64.tar.gz"
        sha256 "ddce53f6c8d87da870dca44e04109cb5b4b5728a63bf5129d49b9c95c8d12192"

        def install
          bin.install "go-ssh"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/mr-kaynak/go-ssh/releases/download/v0.1.3/go-ssh_0.1.3_linux_arm64.tar.gz"
        sha256 "99ea1771a67e55d2aeb95dc936eec7dbe9d62cc1b87e011b81c75500d56ad50e"

        def install
          bin.install "go-ssh"
        end
      end
    end
  end

  test do
    system "#{bin}/go-ssh --version"
  end
end
