# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GoSsh < Formula
  desc "Minimalist SSH key management tool with interactive TUI"
  homepage "https://github.com/mr-kaynak/go-ssh"
  version "0.1.3"
  license "MIT"

  on_macos do
    on_intel do
      url "https://github.com/mr-kaynak/go-ssh/releases/download/v0.1.3/go-ssh_0.1.3_darwin_amd64.tar.gz"
      sha256 "7c4f10ec109e7395e613f7d86af772f300396f9606c98ad5543683842e98e007"

      def install
        bin.install "go-ssh"
      end
    end
    on_arm do
      url "https://github.com/mr-kaynak/go-ssh/releases/download/v0.1.3/go-ssh_0.1.3_darwin_arm64.tar.gz"
      sha256 "c2641e72fd095d2aebaa0f6ad5c5e05e7506cb1b0d53522475b415541231e2ec"

      def install
        bin.install "go-ssh"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/mr-kaynak/go-ssh/releases/download/v0.1.3/go-ssh_0.1.3_linux_amd64.tar.gz"
        sha256 "38850b2daa1e75f260aac9f4bd9e9363ee7df1e9905720b931977dab5de05e88"

        def install
          bin.install "go-ssh"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/mr-kaynak/go-ssh/releases/download/v0.1.3/go-ssh_0.1.3_linux_arm64.tar.gz"
        sha256 "85d2dacc0233e7db4b67bfdbd92345f421f5e97d4dc926e06962b9e799c8f011"

        def install
          bin.install "go-ssh"
        end
      end
    end
  end

  test do
    system "#{bin}/go-ssh --version"
  end
end
