# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GoSsh < Formula
  desc "Minimalist SSH key management tool with interactive TUI"
  homepage "https://github.com/mr-kaynak/go-ssh"
  version "0.1.1"
  license "MIT"

  on_macos do
    on_intel do
      url "https://github.com/mr-kaynak/go-ssh/releases/download/v0.1.1/go-ssh_0.1.1_darwin_amd64.tar.gz"
      sha256 "55b9564f59e3980c872a76f3144da43d4cafd7401b3aaee2ae5ded989c54ba3b"

      def install
        bin.install "go-ssh"
      end
    end
    on_arm do
      url "https://github.com/mr-kaynak/go-ssh/releases/download/v0.1.1/go-ssh_0.1.1_darwin_arm64.tar.gz"
      sha256 "0be802a370558c6e748f36db5fe35efafd99b3fe7aa1624f8669db67a161538d"

      def install
        bin.install "go-ssh"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/mr-kaynak/go-ssh/releases/download/v0.1.1/go-ssh_0.1.1_linux_amd64.tar.gz"
        sha256 "43616ebd66997ebc3a4c53072a1db10b88ed8e353dbf187e65b655de818fdfbb"

        def install
          bin.install "go-ssh"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/mr-kaynak/go-ssh/releases/download/v0.1.1/go-ssh_0.1.1_linux_arm64.tar.gz"
        sha256 "c37576c6cde867c3cbbe22273348f02d3c693264e0faa0b67259c41b0ef2bfaf"

        def install
          bin.install "go-ssh"
        end
      end
    end
  end

  test do
    system "#{bin}/go-ssh --version"
  end
end
